# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://BorjaRequena.github.io/qfi/"

git_url = "https://github.com/BorjaRequena/qfi/tree/master/"

def custom_doc_links(name): return None
