# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"random_unitary_circuits": "randomized.ipynb",
         "randomized_measurement_overlap": "randomized.ipynb"}

modules = ["qfi.py",
           "overlap/randomized.py"]

doc_url = "https://BorjaRequena.github.io/fisherman/"

git_url = "https://github.com/BorjaRequena/fisherman/tree/master/"

def custom_doc_links(name): return None
