# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"random_unitary_circuits": "00_randomized.ipynb",
         "randomized_measurement_overlap": "00_randomized.ipynb",
         "swap_test_overlap": "02_swap.ipynb",
         "swap_test_operator": "02_swap.ipynb",
         "compute_uncompute_overlap": "03_compuncomp.ipynb",
         "is_exact_simulation": "05_utils.ipynb",
         "sym_from_triu": "05_utils.ipynb",
         "vector_basis": "05_utils.ipynb",
         "hamming_distance": "05_utils.ipynb"}

modules = ["randomized.py",
           "swap.py",
           "comp_uncomp.py",
           "utils.py"]

doc_url = "https://BorjaRequena.github.io/Quantum-Fisherman/"

git_url = "https://github.com/BorjaRequena/Quantum-Fisherman/tree/master/"

def custom_doc_links(name): return None
