# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"random_unitary_circuits": "00_randomized.ipynb",
         "randomized_measurement_overlap": "00_randomized.ipynb",
         "device_independent_overlap": "00_randomized.ipynb",
         "swap_test_overlap": "01_swap.ipynb",
         "compute_uncompute_overlap": "02_compuncomp.ipynb",
         "is_exact_simulation": "03_utils.ipynb",
         "sym_from_triu": "03_utils.ipynb",
         "vector_basis": "03_utils.ipynb",
         "hamming_distance": "03_utils.ipynb"}

modules = ["overlap/randomized.py",
           "overlap/swap.py",
           "overlap/comp_uncomp.py",
           "utils.py"]

doc_url = "https://BorjaRequena.github.io/Quantum-Fisherman/"

git_url = "https://github.com/BorjaRequena/Quantum-Fisherman/tree/master/"

def custom_doc_links(name): return None
