# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/05_utils.ipynb (unless otherwise specified).

__all__ = ['is_exact_simulation', 'sym_from_triu', 'vector_basis', 'hamming_distance']

# Cell
import numpy as np

# Cell
def is_exact_simulation(quantum_instance):
    "Determines whether the quantum instance is to perform a noiseless exact simulation."
    sim = quantum_instance.is_simulator
    noise_qi = len(quantum_instance.noise_config) == 0
    noise_backend = quantum_instance.backend.options.noise_model is None
    return sim and noise_qi and noise_backend

def sym_from_triu(x, n):
    "Creates an `nxn` symmetric matrix from the upper triangular data `x`."
    sym = np.zeros((n, n))
    sym[np.triu_indices(n)] = x
    sym += np.triu(sym, 1).T
    return sym

def vector_basis(n):
    "Creates a vector basis with the binary encodings from 0 to `n`."
    v = np.arange(2**n)
    return (v[:, None] & (1 << np.arange(n)) > 0).astype(int)

def hamming_distance(x, y):
    "Hamming distance between arrays `x` and `y`."
    return np.count_nonzero(x != y)